In [4]:
import cv2
import numpy as np

In [5]:
image = cv2.imread("moon.jpg")
shp=image.shape
print(shp)
height,width=image.shape[:2]
print(height)
print(width)

(2400, 2400, 3)
2400
2400


In [6]:
cv2.imshow("original_image",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
image1 = cv2.resize(image,(800,800))

NameError: name 'cv2' is not defined

In [3]:
center = (height/4,width/4)
print(center)

NameError: name 'height' is not defined

In [31]:
#using cv2.getrotationMatrix2D to get the rotation matrix
rotate_matrix = cv2.getRotationMatrix2D(center=center, angle=1, scale=1.0)
print(rotate_matrix)

[[ 9.99847695e-01  1.74524064e-02 -2.07601219e+01]
 [-1.74524064e-02  9.99847695e-01  2.11256535e+01]]


In [32]:
#rotate the image using cv.2warpaffine
rotated_image = cv2.warpAffine(src=image1, M=rotate_matrix, dsize=(width,height))

cv2.imshow('Original_image',image1)
cv2.waitKey(0)
cv2.imshow('Rotate_image',rotated_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
#translation

In [34]:
tx,ty = 100.0,50.0
print(tx)
print(ty)

100.0
50.0


In [45]:
# create the translation matrix using tx and ty, it is a numpy array
translation_matrix = np.array([[1,0,tx],[0,1,ty]])

In [51]:
# apply the translation to the image
translated_image = cv2.warpAffine(src=horse1, M= translation_matrix, dsize=(width,height))

In [53]:
cv2.imshow('translation_image',translated_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
horse = cv2.imread('horse.png')

In [10]:
horse1= cv2.resize(horse,(800,800))

In [66]:
bitwise_or = cv2.bitwise_or(horse1,image1,mask = None)

In [67]:
bitwise_and = cv2.bitwise_and(image1,horse1,mask = None)

In [68]:
bitwise_xor = cv2.bitwise_xor(image1,horse1,mask = None)

In [69]:
cv2.imshow("image1",horse1)
cv2.imshow("image2",horse1)
cv2.imshow("bitwise and" ,bitwise_and)
cv2.imshow("bitwise or" ,bitwise_or)
cv2.imshow("bitwise xor", bitwise_xor)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
horse1 = cv2.imread("horse.png")
horse1 = cv2.resize(horse,(400,400))
cv2.imshow('resize',horse1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
imAdd= cv2.addWeighted(image1,0.8,horse1,0.3,30)
cv2.imshow('imAdd',imAdd)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'image1' is not defined

In [21]:
rotate_matrix = cv2.getRotationMatrix2D(center=center, angle=180, scale=1.0)
print(rotate_matrix)

[[-1.0000000e+00  1.2246468e-16  1.2000000e+03]
 [-1.2246468e-16 -1.0000000e+00  1.2000000e+03]]


In [24]:
center

(600.0, 600.0)

In [23]:
rotated_image = cv2.warpAffine(src=horse1, M=rotate_matrix, dsize=(500,500))
cv2.imshow('Original_image',horse1)
cv2.waitKey(0)
cv2.imshow('Rotate_image',rotated_image)
cv2.waitKey(0)
cv2.destroyAllWindows()